/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/reoring/provider-zitadel/apis/org/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this LoginPolicy.
func (mg *LoginPolicy) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Idps),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.IdpsRefs,
		Selector:      mg.Spec.ForProvider.IdpsSelector,
		To: reference.To{
			List:    &v1alpha1.OrgIDPGithubList{},
			Managed: &v1alpha1.OrgIDPGithub{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Idps")
	}
	mg.Spec.ForProvider.Idps = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.IdpsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OrgIDRef,
		Selector:     mg.Spec.ForProvider.OrgIDSelector,
		To: reference.To{
			List:    &v1alpha1.OrgList{},
			Managed: &v1alpha1.Org{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference

	return nil
}
