//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oidc) DeepCopyInto(out *Oidc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oidc.
func (in *Oidc) DeepCopy() *Oidc {
	if in == nil {
		return nil
	}
	out := new(Oidc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Oidc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcInitParameters) DeepCopyInto(out *OidcInitParameters) {
	*out = *in
	if in.AccessTokenRoleAssertion != nil {
		in, out := &in.AccessTokenRoleAssertion, &out.AccessTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenType != nil {
		in, out := &in.AccessTokenType, &out.AccessTokenType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AppType != nil {
		in, out := &in.AppType, &out.AppType
		*out = new(string)
		**out = **in
	}
	if in.AuthMethodType != nil {
		in, out := &in.AuthMethodType, &out.AuthMethodType
		*out = new(string)
		**out = **in
	}
	if in.ClockSkew != nil {
		in, out := &in.ClockSkew, &out.ClockSkew
		*out = new(string)
		**out = **in
	}
	if in.DevMode != nil {
		in, out := &in.DevMode, &out.DevMode
		*out = new(bool)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IDTokenRoleAssertion != nil {
		in, out := &in.IDTokenRoleAssertion, &out.IDTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenUserinfoAssertion != nil {
		in, out := &in.IDTokenUserinfoAssertion, &out.IDTokenUserinfoAssertion
		*out = new(bool)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcInitParameters.
func (in *OidcInitParameters) DeepCopy() *OidcInitParameters {
	if in == nil {
		return nil
	}
	out := new(OidcInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcList) DeepCopyInto(out *OidcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Oidc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcList.
func (in *OidcList) DeepCopy() *OidcList {
	if in == nil {
		return nil
	}
	out := new(OidcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OidcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcObservation) DeepCopyInto(out *OidcObservation) {
	*out = *in
	if in.AccessTokenRoleAssertion != nil {
		in, out := &in.AccessTokenRoleAssertion, &out.AccessTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenType != nil {
		in, out := &in.AccessTokenType, &out.AccessTokenType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AppType != nil {
		in, out := &in.AppType, &out.AppType
		*out = new(string)
		**out = **in
	}
	if in.AuthMethodType != nil {
		in, out := &in.AuthMethodType, &out.AuthMethodType
		*out = new(string)
		**out = **in
	}
	if in.ClockSkew != nil {
		in, out := &in.ClockSkew, &out.ClockSkew
		*out = new(string)
		**out = **in
	}
	if in.DevMode != nil {
		in, out := &in.DevMode, &out.DevMode
		*out = new(bool)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDTokenRoleAssertion != nil {
		in, out := &in.IDTokenRoleAssertion, &out.IDTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenUserinfoAssertion != nil {
		in, out := &in.IDTokenUserinfoAssertion, &out.IDTokenUserinfoAssertion
		*out = new(bool)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcObservation.
func (in *OidcObservation) DeepCopy() *OidcObservation {
	if in == nil {
		return nil
	}
	out := new(OidcObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcParameters) DeepCopyInto(out *OidcParameters) {
	*out = *in
	if in.AccessTokenRoleAssertion != nil {
		in, out := &in.AccessTokenRoleAssertion, &out.AccessTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenType != nil {
		in, out := &in.AccessTokenType, &out.AccessTokenType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AppType != nil {
		in, out := &in.AppType, &out.AppType
		*out = new(string)
		**out = **in
	}
	if in.AuthMethodType != nil {
		in, out := &in.AuthMethodType, &out.AuthMethodType
		*out = new(string)
		**out = **in
	}
	if in.ClockSkew != nil {
		in, out := &in.ClockSkew, &out.ClockSkew
		*out = new(string)
		**out = **in
	}
	if in.DevMode != nil {
		in, out := &in.DevMode, &out.DevMode
		*out = new(bool)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IDTokenRoleAssertion != nil {
		in, out := &in.IDTokenRoleAssertion, &out.IDTokenRoleAssertion
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenUserinfoAssertion != nil {
		in, out := &in.IDTokenUserinfoAssertion, &out.IDTokenUserinfoAssertion
		*out = new(bool)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcParameters.
func (in *OidcParameters) DeepCopy() *OidcParameters {
	if in == nil {
		return nil
	}
	out := new(OidcParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcSpec) DeepCopyInto(out *OidcSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcSpec.
func (in *OidcSpec) DeepCopy() *OidcSpec {
	if in == nil {
		return nil
	}
	out := new(OidcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcStatus) DeepCopyInto(out *OidcStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcStatus.
func (in *OidcStatus) DeepCopy() *OidcStatus {
	if in == nil {
		return nil
	}
	out := new(OidcStatus)
	in.DeepCopyInto(out)
	return out
}
