apiVersion: action.reoring.io/v1alpha1
kind: Action
metadata:
  annotations:
    meta.upbound.io/example-id: action/v1alpha1/action
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allowedToFail: true
    orgId: ${data.zitadel_org.default.id}
    script: testscript
    timeout: 10s
