apiVersion: org.reoring.io/v1alpha1
kind: OrgIDPGithub
metadata:
  annotations:
    meta.upbound.io/example-id: org/v1alpha1/orgidpgithub
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientId: 86a165...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    orgId: ${data.zitadel_org.default.id}
    scopes:
    - openid
    - profile
    - email
